### ISSUE TITLE
Consider migrating to libhdfs3

### ISSUE THREAD

**Issue by superbobry** [dmlc/dmlc-core#267]
> Libhdfs3, designed as an alternative implementation of libhdfs, is implemented based on native Hadoop RPC protocol and HDFS data transfer protocol. It gets rid of the drawbacks of JNI, and it has a lightweight, small memory footprint code base. In addition, it is easy to use and deploy.

I think ease of deployment enough is a good reason to drop the original libhdfs.

**Comment by wesm** [comment]
We are supporting both libhdfs and libhdfs3 in Apache Arrow's IO subsystem since they export more or less the same C API (so we can dlopen the one we want to use); I found that libhdfs3 was weaker in net throughput and especially weak in small reads

http://wesmckinney.com/blog/python-hdfs-interfaces/

Combined with the fact that libhdfs3's future is rather uncertain (see its current home at https://github.com/apache/incubator-hawq/tree/master/depends/libhdfs3) it may not make sense to use for all user. 

There is also work on a new C++ HDFS client within the Apache Hadoop project officially, see https://issues.apache.org/jira/browse/HDFS-8707

**Comment by superbobry** [comment]
Hi @wesm, thanks for the insights. I agree that supporting both libraries might be a more sensible solution, especially given the API similarities.

> Combined with the fact that libhdfs3's future is rather uncertain [...]

Are you referring to the commit date or a something in the README? Judging just by the commit date, the official C++ HDFS client is even more stale.

**Comment by wesm** [comment]
I linked to an umbrella JIRA in Hadoop. I would have to look more closely but it appears that is still under active development -- there are quite a few outstanding patches
